#
# Makefile for the fingerprint drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FINGERPRINT_GOODIX_TA)	+= goodix_ta/
subdir-ccflags-y := -finline-functions -ftree-vectorize -funroll-loops
